# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

pool:
  name: "Self hosted agent"
  
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet'
   
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: $(Build.SourcesDirectory)/products_catalogue.sln
        verbosityRestore: Quiet

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: $(Build.SourcesDirectory)/products_catalogue.sln
        verbosityRestore: Minimal

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: $(Build.SourcesDirectory)/products_catalogue.sln
        msbuildArgs: /v:m
        platform: 'Any CPU'
        configuration: 'Release'
        maximumCpuCount: true
        msbuildArchitecture: x64
        logProjectEvents: false
